### ISSUE TITLE
A20 - 10 extra bytes

### ISSUE THREAD

**Issue by kathleenm678** [OtisElevatorCompany/udp_rx#10]
In A20, 10 extra bytes get added to the end of messages.

**Comment by LivingInSyn** [comment]
Issue lies in header parsing. the header bytes are removed, but the buffer size is not adjusted on the sending path

**Comment by LivingInSyn** [comment]
closed in https://github.com/OtisElevatorCompany/udp_rx/commit/88cd703bed8ec1ef1fb3378a541c54f0d4dab2c7
