### ISSUE TITLE
Set static location of logs

### ISSUE THREAD

**Issue by SputnikTheDog** [OtisElevatorCompany/udp_rx#20]
The udp_rx log file should be written to /var/log on linux and the windows log on windows.

**Comment by LivingInSyn** [comment]
Instead of a location, change the following line:

https://github.com/OtisElevatorCompany/udp_rx/blob/master/udp_rx.go#L81

To a configurable value based on windows vs *nix

**Comment by LivingInSyn** [comment]
closed in AAA 1.0 release
